// tools/docs-gen generates Markdown documentation for all gg CLI commands
// using cobra's built-in doc generator and writes the output to docs/cli/.
//
// Usage:
//
//	go run ./tools/docs-gen
//
// The CI drift check runs this and then checks for uncommitted changes:
//
//	go run ./tools/docs-gen && git diff --exit-code docs/cli/
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/gurkangul/gg-cli/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	// Cobra help includes flag defaults. Clear agent/runtime env that can change
	// those defaults so generated docs are deterministic in human and agent shells.
	for _, key := range []string{"GG_AGENT", "GG_ROLE", "GG_FROM"} {
		if err := os.Unsetenv(key); err != nil {
			fmt.Fprintf(os.Stderr, "error: unset %s: %v\n", key, err)
			os.Exit(1)
		}
	}

	// Resolve the repo root relative to this file so the tool works
	// regardless of where it is invoked from.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "error: runtime.Caller failed")
		os.Exit(1)
	}
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")
	outDir := filepath.Join(repoRoot, "docs", "cli")

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error: create %s: %v\n", outDir, err)
		os.Exit(1)
	}

	root := cmd.RootCmd()

	// DisableAutoGenTag removes the "Auto generated by spf13/cobra" footer so
	// the generated files are deterministic across Go/cobra version bumps.
	root.DisableAutoGenTag = true

	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: generate docs: %v\n", err)
		os.Exit(1)
	}
	if err := normalizeMarkdownEOF(outDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: normalize docs: %v\n", err)
		os.Exit(1)
	}

	// Count generated files for a friendly confirmation message.
	entries, _ := os.ReadDir(outDir)
	var mdCount int
	for _, e := range entries {
		if filepath.Ext(e.Name()) == ".md" {
			mdCount++
		}
	}

	fmt.Printf("Generated %d markdown files in %s\n", mdCount, outDir)
}

func normalizeMarkdownEOF(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		normalized := strings.TrimRight(string(data), "\n") + "\n"
		if normalized == string(data) {
			continue
		}
		if err := os.WriteFile(path, []byte(normalized), 0o644); err != nil {
			return err
		}
	}
	return nil
}
