// tools/docs-gen generates Markdown documentation for all gg CLI commands
// using cobra's built-in doc generator and writes the output to docs/cli/.
//
// Usage:
//
//	go run ./tools/docs-gen
//
// The CI drift check runs this and then checks for uncommitted changes:
//
//	go run ./tools/docs-gen && git diff --exit-code docs/cli/
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/gurkangul/gg-cli/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	// Cobra help includes flag defaults. Clear agent/runtime env that can change
	// those defaults so generated docs are deterministic in human and agent shells.
	for _, key := range []string{"GG_AGENT", "GG_ROLE", "GG_FROM"} {
		if err := os.Unsetenv(key); err != nil {
			fmt.Fprintf(os.Stderr, "error: unset %s: %v\n", key, err)
			os.Exit(1)
		}
	}

	// Resolve the repo root relative to this file so the tool works
	// regardless of where it is invoked from.
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "error: runtime.Caller failed")
		os.Exit(1)
	}
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")
	outDir := filepath.Join(repoRoot, "docs", "cli")

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "error: create %s: %v\n", outDir, err)
		os.Exit(1)
	}

	root := cmd.RootCmd()

	// DisableAutoGenTag removes the "Auto generated by spf13/cobra" footer so
	// the generated files are deterministic across Go/cobra version bumps.
	root.DisableAutoGenTag = true

	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: generate docs: %v\n", err)
		os.Exit(1)
	}
	removed, err := pruneOrphanedDocs(root, outDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: prune docs: %v\n", err)
		os.Exit(1)
	}
	if err := normalizeMarkdownEOF(outDir); err != nil {
		fmt.Fprintf(os.Stderr, "error: normalize docs: %v\n", err)
		os.Exit(1)
	}

	// Count generated files for a friendly confirmation message.
	entries, _ := os.ReadDir(outDir)
	var mdCount int
	for _, e := range entries {
		if filepath.Ext(e.Name()) == ".md" {
			mdCount++
		}
	}

	if removed > 0 {
		fmt.Printf("Pruned %d orphaned markdown file(s)\n", removed)
	}
	fmt.Printf("Generated %d markdown files in %s\n", mdCount, outDir)
}

// pruneOrphanedDocs deletes docs/cli pages that no longer correspond to a
// command cobra emits.
//
// BUG-108: GenMarkdownTree skips commands whose Deprecated field is set
// (IsAvailableCommand() reports false), but the page generated before the
// deprecation stays on disk and is never refreshed again — so its flag
// documentation freezes and silently drifts from the real --help. CI could not
// catch it either: the drift check runs this tool and then `git diff
// --exit-code docs/cli/`, and a file nobody rewrites produces no diff. Deleting
// the orphan is what gives that check something to see.
func pruneOrphanedDocs(root *cobra.Command, outDir string) (int, error) {
	expected := map[string]bool{}
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		// Mirrors GenMarkdownTree's own filter, so "expected" means exactly the
		// set of pages it just wrote.
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			return
		}
		expected[strings.ReplaceAll(c.CommandPath(), " ", "_")+".md"] = true
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)

	entries, err := os.ReadDir(outDir)
	if err != nil {
		return 0, err
	}
	removed := 0
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || filepath.Ext(name) != ".md" || expected[name] {
			continue
		}
		if err := os.Remove(filepath.Join(outDir, name)); err != nil {
			return removed, err
		}
		fmt.Printf("pruned orphaned doc: %s\n", name)
		removed++
	}
	return removed, nil
}

func normalizeMarkdownEOF(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		normalized := strings.TrimRight(string(data), "\n") + "\n"
		if normalized == string(data) {
			continue
		}
		//nolint:gosec // G703: path is built from this tool's own output dir + generated filename, not user input
		if err := os.WriteFile(path, []byte(normalized), 0o644); err != nil {
			return err
		}
	}
	return nil
}
