package cmd

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// TestGitleaksPlatformKey verifies the platform→slug mapping for the current
// running platform and that an unsupported platform returns an error.
func TestGitleaksPlatformKey(t *testing.T) {
	got, err := gitleaksPlatformKey()
	switch {
	case runtime.GOOS == "darwin" && runtime.GOARCH == "arm64":
		if err != nil || got != "darwin_arm64" {
			t.Errorf("darwin/arm64: got (%q, %v)", got, err)
		}
	case runtime.GOOS == "darwin" && runtime.GOARCH == "amd64":
		if err != nil || got != "darwin_x64" {
			t.Errorf("darwin/amd64: got (%q, %v)", got, err)
		}
	case runtime.GOOS == "linux" && runtime.GOARCH == "arm64":
		if err != nil || got != "linux_arm64" {
			t.Errorf("linux/arm64: got (%q, %v)", got, err)
		}
	case runtime.GOOS == "linux" && runtime.GOARCH == "amd64":
		if err != nil || got != "linux_x64" {
			t.Errorf("linux/amd64: got (%q, %v)", got, err)
		}
	case runtime.GOOS == "windows" && runtime.GOARCH == "amd64":
		if err != nil || got != "windows_x64" {
			t.Errorf("windows/amd64: got (%q, %v)", got, err)
		}
	default:
		// Unsupported platform should return error.
		if err == nil {
			t.Errorf("unexpected platform %s/%s: expected error, got key %q", runtime.GOOS, runtime.GOARCH, got)
		}
	}
}

// TestFetchExpectedSHA_Found verifies the happy path: the SHA is returned
// when the archive name appears in a well-formed checksums.txt response.
func TestFetchExpectedSHA_Found(t *testing.T) {
	const archiveName = "gitleaks_8.21.2_darwin_arm64.tar.gz"
	const expectedSHA = "aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899"

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "# comment line\n\n")
		fmt.Fprintf(w, "%s  gitleaks_8.21.2_linux_x64.tar.gz\n", strings.Repeat("0", 64))
		fmt.Fprintf(w, "%s  %s\n", expectedSHA, archiveName)
	}))
	defer srv.Close()

	got, err := fetchExpectedSHA(srv.Client(), srv.URL, archiveName)
	if err != nil {
		t.Fatalf("fetchExpectedSHA: unexpected error: %v", err)
	}
	if got != expectedSHA {
		t.Errorf("fetchExpectedSHA = %q, want %q", got, expectedSHA)
	}
}

// TestFetchExpectedSHA_NotFound verifies an error is returned when the
// archive name is absent from the checksums file.
func TestFetchExpectedSHA_NotFound(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "%s  some_other_archive.tar.gz\n", strings.Repeat("a", 64))
	}))
	defer srv.Close()

	_, err := fetchExpectedSHA(srv.Client(), srv.URL, "missing_archive.tar.gz")
	if err == nil {
		t.Fatal("expected error for missing archive name, got nil")
	}
	if !strings.Contains(err.Error(), "missing_archive.tar.gz") {
		t.Errorf("error message should contain archive name, got: %v", err)
	}
}

// TestFetchExpectedSHA_EmptyBody verifies an error when the response body is empty.
func TestFetchExpectedSHA_EmptyBody(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// empty body
	}))
	defer srv.Close()

	_, err := fetchExpectedSHA(srv.Client(), srv.URL, "any.tar.gz")
	if err == nil {
		t.Fatal("expected error for empty checksums body, got nil")
	}
}

// TestFetchExpectedSHA_BlankLines verifies that blank lines and comment lines
// in the checksums file are skipped without causing a parse error.
func TestFetchExpectedSHA_BlankLines(t *testing.T) {
	const archiveName = "gitleaks_8.21.2_linux_x64.tar.gz"
	expectedSHA := strings.Repeat("c", 64)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "\n\n# generated by goreleaser\n\n   \n")
		fmt.Fprintf(w, "%s  %s\n", expectedSHA, archiveName)
	}))
	defer srv.Close()

	got, err := fetchExpectedSHA(srv.Client(), srv.URL, archiveName)
	if err != nil {
		t.Fatalf("fetchExpectedSHA with blank/comment lines: %v", err)
	}
	if got != expectedSHA {
		t.Errorf("got %q, want %q", got, expectedSHA)
	}
}

// TestFetchExpectedSHA_HTTPError verifies an error is returned on non-200 status.
func TestFetchExpectedSHA_HTTPError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
	}))
	defer srv.Close()

	_, err := fetchExpectedSHA(srv.Client(), srv.URL, "any.tar.gz")
	if err == nil {
		t.Fatal("expected error on HTTP 404, got nil")
	}
}

// TestFetchExpectedSHA_MissingEntryError verifies the error message includes
// the archive name so the caller knows which entry was missing.
func TestFetchExpectedSHA_MissingEntryError(t *testing.T) {
	const want = "wanted-archive.tar.gz"
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "%s  other-archive.tar.gz\n", strings.Repeat("f", 64))
	}))
	defer srv.Close()

	_, err := fetchExpectedSHA(srv.Client(), srv.URL, want)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), want) {
		t.Errorf("error %q does not contain archive name %q", err, want)
	}
}

// TestErrGitleaksAlreadyInstalled_Sentinel verifies that ErrGitleaksAlreadyInstalled
// is a distinguishable sentinel via errors.Is.
func TestErrGitleaksAlreadyInstalled_Sentinel(t *testing.T) {
	wrapped := fmt.Errorf("%w at /some/path", ErrGitleaksAlreadyInstalled)
	if !errors.Is(wrapped, ErrGitleaksAlreadyInstalled) {
		t.Error("errors.Is should unwrap to ErrGitleaksAlreadyInstalled")
	}
}

// TestChecksumMismatch verifies that when the archive SHA does not match the
// expected SHA, the mismatch is detectable. Uses httptest servers to avoid
// real network calls.
func TestChecksumMismatch(t *testing.T) {
	const archiveName = "gitleaks_8.21.2_linux_x64.tar.gz"
	fakeExpectedSHA := strings.Repeat("0", 64)

	srvChecksums := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "%s  %s\n", fakeExpectedSHA, archiveName)
	}))
	defer srvChecksums.Close()

	srvArchive := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "this is not a real archive — its SHA will differ from fakeExpectedSHA")
	}))
	defer srvArchive.Close()

	client := srvChecksums.Client()

	gotExpected, err := fetchExpectedSHA(client, srvChecksums.URL, archiveName)
	if err != nil {
		t.Fatalf("fetchExpectedSHA: %v", err)
	}

	resp, err := client.Get(srvArchive.URL) //nolint:noctx
	if err != nil {
		t.Fatalf("get archive: %v", err)
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(resp.Body)
	sum := sha256.Sum256(data)
	gotSHA := hex.EncodeToString(sum[:])

	// The real installer compares gotSHA != expectedSHA to detect mismatch.
	if gotSHA == gotExpected {
		t.Fatal("test setup error: archive SHA unexpectedly matches fake expected SHA")
	}
}

// TestInstallGitPreCommitDispatcher_Fresh verifies the dispatcher is written
// when no .git/hooks/pre-commit exists.
func TestInstallGitPreCommitDispatcher_Fresh(t *testing.T) {
	root := t.TempDir()
	gitHooksDir := filepath.Join(root, ".git", "hooks")
	if err := os.MkdirAll(gitHooksDir, 0o755); err != nil {
		t.Fatal(err)
	}

	preCommitDir := filepath.Join(root, ".gg", "hooks", "pre-commit.d")
	if err := installGitPreCommitDispatcher(root, preCommitDir); err != nil {
		t.Fatalf("installGitPreCommitDispatcher: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(gitHooksDir, "pre-commit")) //nolint:gosec
	if err != nil {
		t.Fatalf("pre-commit hook not written: %v", err)
	}
	body := string(data)
	if !strings.Contains(body, "pre-commit.d") {
		t.Error("dispatcher script should reference pre-commit.d")
	}
	if !strings.HasPrefix(body, "#!/bin/sh") {
		t.Error("dispatcher script should start with #!/bin/sh")
	}
}

// TestInstallGitPreCommitDispatcher_ExistingForeignHook verifies that a
// foreign .git/hooks/pre-commit is not overwritten — only the fan-out
// stanza is appended.
func TestInstallGitPreCommitDispatcher_ExistingForeignHook(t *testing.T) {
	root := t.TempDir()
	gitHooksDir := filepath.Join(root, ".git", "hooks")
	if err := os.MkdirAll(gitHooksDir, 0o755); err != nil {
		t.Fatal(err)
	}
	existingBody := "#!/bin/sh\n# existing hook\necho hello\n"
	dispatcherPath := filepath.Join(gitHooksDir, "pre-commit")
	if err := os.WriteFile(dispatcherPath, []byte(existingBody), 0o755); err != nil {
		t.Fatal(err)
	}

	preCommitDir := filepath.Join(root, ".gg", "hooks", "pre-commit.d")
	if err := installGitPreCommitDispatcher(root, preCommitDir); err != nil {
		t.Fatalf("installGitPreCommitDispatcher: %v", err)
	}

	data, err := os.ReadFile(dispatcherPath) //nolint:gosec
	if err != nil {
		t.Fatalf("read dispatcher: %v", err)
	}
	body := string(data)
	if !strings.Contains(body, "existing hook") {
		t.Error("original hook content should be preserved")
	}
	if !strings.Contains(body, "pre-commit.d") {
		t.Error("fan-out stanza should be appended")
	}
}

// TestInstallGitPreCommitDispatcher_Idempotent verifies that running the
// installer twice when the dispatcher already contains pre-commit.d is a no-op.
func TestInstallGitPreCommitDispatcher_Idempotent(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, ".git", "hooks"), 0o755); err != nil {
		t.Fatal(err)
	}

	preCommitDir := filepath.Join(root, ".gg", "hooks", "pre-commit.d")
	if err := installGitPreCommitDispatcher(root, preCommitDir); err != nil {
		t.Fatalf("first install: %v", err)
	}
	firstContent, _ := os.ReadFile(filepath.Join(root, ".git", "hooks", "pre-commit")) //nolint:gosec

	if err := installGitPreCommitDispatcher(root, preCommitDir); err != nil {
		t.Fatalf("second install: %v", err)
	}
	secondContent, _ := os.ReadFile(filepath.Join(root, ".git", "hooks", "pre-commit")) //nolint:gosec

	if string(firstContent) != string(secondContent) {
		t.Error("second install should not modify the dispatcher")
	}
}

// TestInstallGitPreCommitDispatcher_NoGitDir verifies that a missing .git
// directory is treated as a graceful skip (warn + nil) rather than an error,
// so `gg doctor --install-task-hooks` is safe to run before `git init`.
func TestInstallGitPreCommitDispatcher_NoGitDir(t *testing.T) {
	root := t.TempDir() // no .git inside
	err := installGitPreCommitDispatcher(root, filepath.Join(root, "pre-commit.d"))
	if err != nil {
		t.Fatalf("expected nil for missing .git (graceful skip), got: %v", err)
	}
}
