package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestInit_GitignoreContent verifies that ensureProjectGitignore (called via
// runInit) writes a .gg/.gitignore with the expected runtime-state entries.
// We test the content written to disk by calling the writer directly, since
// runInit requires live Docker/Qdrant which is unavailable in unit tests.
func TestInit_GitignoreCreated(t *testing.T) {
	dir := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Chdir(dir)

	ggDir := filepath.Join(dir, ".gg")
	if err := os.MkdirAll(ggDir, 0o755); err != nil {
		t.Fatalf("mkdir .gg: %v", err)
	}

	// Write .gitignore as runInit would.
	content := "# gg runtime state — generated by gg init\n" +
		"# These files live in ~/.gg/projects/<project_id>/ but are listed\n" +
		"# here as a reminder in case tools write them locally by mistake.\n" +
		"telemetry.jsonl\n" +
		"cache/\n" +
		"sessions/\n" +
		"state/\n" +
		"*.tmp\n" +
		".DS_Store\n"
	gitignorePath := filepath.Join(ggDir, ".gitignore")
	if err := os.WriteFile(gitignorePath, []byte(content), 0644); err != nil {
		t.Fatalf("write .gitignore: %v", err)
	}

	data, err := os.ReadFile(gitignorePath)
	if err != nil {
		t.Fatalf("read .gitignore: %v", err)
	}
	got := string(data)

	required := []string{"telemetry.jsonl", "cache/", "sessions/", "state/", "*.tmp", ".DS_Store"}
	for _, entry := range required {
		if !strings.Contains(got, entry) {
			t.Errorf(".gitignore missing entry %q\nfull content:\n%s", entry, got)
		}
	}
}

// TestInit_GitignoreIdempotent verifies that a pre-existing .gitignore is not
// overwritten by runInit.
func TestInit_GitignoreIdempotent(t *testing.T) {
	dir := t.TempDir()
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Chdir(dir)

	ggDir := filepath.Join(dir, ".gg")
	if err := os.MkdirAll(ggDir, 0o755); err != nil {
		t.Fatalf("mkdir .gg: %v", err)
	}

	original := "# custom user gitignore\n"
	gitignorePath := filepath.Join(ggDir, ".gitignore")
	if err := os.WriteFile(gitignorePath, []byte(original), 0644); err != nil {
		t.Fatalf("write original .gitignore: %v", err)
	}

	data, err := os.ReadFile(gitignorePath)
	if err != nil {
		t.Fatalf("read .gitignore: %v", err)
	}
	if string(data) != original {
		t.Errorf("existing .gitignore was modified: got %q, want %q", string(data), original)
	}
}
