package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/gurkangul/gg-cli/internal/config"
	"github.com/gurkangul/gg-cli/internal/store"
	"github.com/gurkangul/gg-cli/internal/telemetry"
	"github.com/gurkangul/gg-cli/internal/trace"
)

var statusRenderCmd = &cobra.Command{
	Use:   "render",
	Short: "Generate STATUS.md from gg brain state",
	Long: `Write STATUS.md to the project root, derived from live gg brain state.

  gg status render          # write STATUS.md
  gg status render --check  # exit non-zero if STATUS.md is stale (CI drift check)

The file begins with '<!-- GENERATED by gg status render. Do not edit. -->'
so any manual edit is visibly overwritten on the next run.`,
	RunE: runStatusRender,
}

var (
	statusRenderCheck bool
	statusRenderOut   string
)

func init() {
	statusRenderCmd.Flags().BoolVar(&statusRenderCheck, "check", false, "exit non-zero if STATUS.md differs from what render would produce (CI drift check)")
	statusRenderCmd.Flags().StringVar(&statusRenderOut, "output", "STATUS.md", "output file path (relative to project root)")
	statusCmd.AddCommand(statusRenderCmd)
}

func runStatusRender(cmd *cobra.Command, _ []string) error {
	d, err := loadDepsReadOnly(false)
	if err != nil {
		return err
	}
	defer d.Close()

	ctx, cancel := withTimeout(cmd.Context())
	defer cancel()

	// Gather data — each call is independent; partial failures degrade gracefully.
	tasks, _ := d.store.ListTasks(ctx, "")
	decisions, _ := d.store.ListDecisions(ctx, 10, false)
	rejections, _ := d.store.ListRejections(ctx, 5)
	messages, _ := d.store.GetInbox(ctx, "", true)

	cfg, cfgErr := config.Load()
	projectName := ""
	if cfgErr == nil {
		projectName = cfg.ProjectID[:8] // short UUID prefix
	}

	md := renderStatusMD(projectName, tasks, decisions, rejections, messages)

	// Resolve output path.
	outPath := statusRenderOut
	if !filepath.IsAbs(outPath) {
		ggDir, ggErr := config.GGDir()
		if ggErr != nil {
			return ggErr
		}
		outPath = filepath.Join(filepath.Dir(ggDir), outPath)
	}

	if statusRenderCheck {
		existing, readErr := os.ReadFile(outPath)
		if readErr != nil && !os.IsNotExist(readErr) {
			return fmt.Errorf("read %s: %w", outPath, readErr)
		}
		if string(existing) == md {
			fmt.Fprintf(cmd.ErrOrStderr(), "✓ STATUS.md is up to date\n")
			return nil
		}
		// Print a compact diff hint.
		fmt.Fprintf(cmd.ErrOrStderr(), "✗ STATUS.md is stale — run: gg status render\n")
		return fmt.Errorf("STATUS.md drift detected")
	}

	if writeErr := os.WriteFile(outPath, []byte(md), 0o644); writeErr != nil {
		return fmt.Errorf("write %s: %w", outPath, writeErr)
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "✓ STATUS.md written to %s\n", outPath)
	return nil
}

func renderStatusMD(projectID string, tasks []store.Task, decisions []store.Decision, rejections []store.Rejection, messages []store.Message) string {
	var b bytes.Buffer

	b.WriteString("<!-- GENERATED by gg status render. Do not edit. -->\n")
	fmt.Fprintf(&b, "<!-- Generated: %s -->\n\n", time.Now().UTC().Format(time.RFC3339))
	b.WriteString("# Project Status\n\n")

	// ── Active tasks ──────────────────────────────────────────────────────────
	b.WriteString("## Active Tasks\n\n")

	type pri struct {
		name  string
		tasks []store.Task
	}
	byPriority := []pri{{"high", nil}, {"medium", nil}, {"low", nil}, {"", nil}}
	pMap := map[string]*[]store.Task{"high": &byPriority[0].tasks, "medium": &byPriority[1].tasks, "low": &byPriority[2].tasks}

	var blocked []store.Task
	for _, t := range tasks {
		switch t.Status {
		case "done":
			continue
		case "blocked":
			blocked = append(blocked, t)
		default:
			if list, ok := pMap[t.Priority]; ok {
				*list = append(*list, t)
			} else {
				byPriority[3].tasks = append(byPriority[3].tasks, t)
			}
		}
	}

	hasActive := false
	for _, p := range byPriority {
		if len(p.tasks) == 0 {
			continue
		}
		hasActive = true
		label := p.name
		if label == "" {
			label = "other"
		}
		fmt.Fprintf(&b, "### %s priority\n\n", strings.Title(label)) //nolint:staticcheck
		for _, t := range p.tasks {
			icon := "○"
			if t.Status == "in_progress" {
				icon = "→"
			}
			fmt.Fprintf(&b, "- %s **%s** %s\n", icon, t.ID, t.Title)
		}
		b.WriteString("\n")
	}
	if !hasActive {
		b.WriteString("_No active tasks._\n\n")
	}

	// ── Blocked tasks ─────────────────────────────────────────────────────────
	if len(blocked) > 0 {
		b.WriteString("## Blocked\n\n")
		for _, t := range blocked {
			fmt.Fprintf(&b, "- ⚠ **%s** %s", t.ID, t.Title)
			if t.BlockReason != "" {
				fmt.Fprintf(&b, " — %s", t.BlockReason)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// ── Recent decisions ──────────────────────────────────────────────────────
	if len(decisions) > 0 {
		b.WriteString("## Recent Decisions\n\n")
		for _, d := range decisions {
			text := d.Text
			if len(text) > 120 {
				text = text[:117] + "…"
			}
			fmt.Fprintf(&b, "- ✓ %s", text)
			if d.Reason != "" {
				reason := d.Reason
				if len(reason) > 80 {
					reason = reason[:77] + "…"
				}
				fmt.Fprintf(&b, " _(reason: %s)_", reason)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// ── Recent rejections ─────────────────────────────────────────────────────
	if len(rejections) > 0 {
		b.WriteString("## Recent Rejections\n\n")
		for _, r := range rejections {
			approach := r.Approach
			if len(approach) > 100 {
				approach = approach[:97] + "…"
			}
			fmt.Fprintf(&b, "- ✗ %s\n", approach)
		}
		b.WriteString("\n")
	}

	// ── Unread messages ───────────────────────────────────────────────────────
	if len(messages) > 0 {
		b.WriteString("## Unread Messages\n\n")
		for _, m := range messages {
			content := m.Content
			if len(content) > 100 {
				content = content[:97] + "…"
			}
			fmt.Fprintf(&b, "- [%s → %s] %s\n", m.FromRole, m.ToRole, content)
		}
		b.WriteString("\n")
	}

	if projectID != "" {
		fmt.Fprintf(&b, "---\n_Project: %s_\n", projectID)
	}

	return b.String()
}

// renderNorthStarBlock prints the North Star metric, compact stats, session
// pressure, and dupe-check counters for the given runtime directory.
func renderNorthStarBlock(rtDir string) {
	tsum, err := telemetry.Summarize(rtDir)
	if err != nil {
		return
	}
	agentPct := pct(tsum.AgentCalls, tsum.Total)
	if tsum.Total > 0 {
		fmt.Printf("North Star  Last 7d: %d calls, %d%% agent-initiated\n", tsum.Total, agentPct)
	} else {
		fmt.Println("North Star  Last 7d: no calls recorded yet")
	}
	if tsum.CompactCalls > 0 && tsum.CompactBytesDefault > 0 {
		saved := tsum.CompactBytesDefault - tsum.CompactBytesOut
		pctSaved := float64(saved) / float64(tsum.CompactBytesDefault) * 100
		fmt.Printf("Compact     %d calls, %s / ~%s tok (est. calibrated: %d bytes/tok) saved (avg %.0f%% reduction)\n",
			tsum.CompactCalls, humanFileSize(int64(saved)),
			humanTokenCount(tsum.CompactTokensSaved), telemetry.CorpusCalibration.Rounded, pctSaved)
		netBytes := tsum.NetSavingsBytes
		netTok := tsum.NetTokensSaved
		netSign := ""
		if netBytes < 0 {
			netSign = "-"
			netBytes = -netBytes
			netTok = -netTok
		}
		refetchPct := float64(tsum.HydrationCalls) / float64(tsum.CompactCalls) * 100
		refetchWarn := hydrationRiskSuffix(tsum.HydrationCalls, tsum.CompactCalls)
		fmt.Printf("  Hydration %d re-fetches (%.0f%%), %s back; net %s%s / ~%s%s tok (est. calibrated: %d bytes/tok)%s\n",
			tsum.HydrationCalls, refetchPct,
			humanFileSize(int64(tsum.HydrationBytesTotal)),
			netSign, humanFileSize(int64(netBytes)),
			netSign, humanTokenCount(netTok), telemetry.CorpusCalibration.Rounded, refetchWarn)
		if tsum.GlyphByteOverhead > 0 {
			glyphPerCall := tsum.GlyphByteOverhead / tsum.CompactCalls
			glyphTokPerCall := float64(glyphPerCall) / float64(telemetry.BytesPerToken)
			fmt.Printf("  Glyphs    ~%s tok (est. calibrated: %d bytes/tok) overhead vs ASCII (%d B/call, %.1f tok/call)\n",
				humanTokenCount(tsum.GlyphTokenOverhead), telemetry.CorpusCalibration.Rounded,
				glyphPerCall, glyphTokPerCall)
		}
		if missed := tsum.MissedCompactByVerb(3); len(missed) > 0 {
			fmt.Println("  Missed    top compact-eligible verbs that ran default (est. savings):")
			for _, r := range missed {
				estTok := r.EstimatedBytesMissed / telemetry.BytesPerToken
				fmt.Printf("    %-12s %d/%d default, ~%s / ~%s tok est. missed\n",
					r.Verb, r.MissedCalls, r.TotalCalls,
					humanFileSize(int64(r.EstimatedBytesMissed)), humanTokenCount(estTok))
			}
			fmt.Println("    (run 'gg telemetry compact-missed' for full breakdown)")
		}
	}
	if ssum, sErr := telemetry.SummarizeSessions(rtDir, time.Now().UTC().AddDate(0, 0, -7)); sErr == nil && ssum.ActiveSessions > 0 {
		fmt.Print(renderSessionsBlock(ssum))
	}
	if tsum.DupeCheckMatchesHits > 0 {
		fmt.Printf("Dupe-check  %d fires, cancel=%d force=%d auto-force=%d\n",
			tsum.DupeCheckMatchesHits,
			tsum.DupeChoiceCancel, tsum.DupeChoiceForce, tsum.DupeChoiceAutoForce)
	}
	fmt.Println()
}

func hydrationRiskSuffix(hydrationCalls, compactCalls int) string {
	if compactCalls <= 0 {
		return ""
	}
	refetchPct := float64(hydrationCalls) / float64(compactCalls) * 100
	switch {
	case refetchPct > 50:
		return " ⚠ drop-list muhtemelen agresif"
	case refetchPct < 10:
		return " ⚠ low; compact may be used as source-of-truth"
	case refetchPct < 20:
		return " ⚠ moderate; hydrate before action"
	default:
		return ""
	}
}

// renderSessionsBlock formats the Sessions summary line and, when
// OverThresholdCount > 0, the ⚠ Sessions warning line. Callers must
// only call this when ssum.ActiveSessions > 0.
func renderSessionsBlock(ssum *telemetry.SessionSummary) string {
	out := fmt.Sprintf("  Sessions    %d active, avg %.1f compact calls/session, p50 %.1f KB p95 %.1f KB cumulative\n",
		ssum.ActiveSessions, ssum.AvgCompactCallsPerSession,
		ssum.P50CumulativeKB, ssum.P95CumulativeKB)
	if ssum.OverThresholdCount > 0 {
		out += fmt.Sprintf("  ⚠ Sessions  %d session(s) exceeded 100 KB compact output — agent context filling fast\n",
			ssum.OverThresholdCount)
	}
	return out
}

// renderTelemetryVerbBlock prints the TELEMETRY header and verb-count table.
func renderTelemetryVerbBlock(rtDir string) {
	tsum, err := telemetry.Summarize(rtDir)
	if err != nil || tsum.Total == 0 {
		return
	}
	fmt.Printf("\nTELEMETRY (last 7 days — %d calls, %d%% agent-initiated):\n",
		tsum.Total, pct(tsum.AgentCalls, tsum.Total))
	type kv struct {
		verb  string
		count int
	}
	var verbs []kv
	for v, c := range tsum.VerbCounts {
		verbs = append(verbs, kv{v, c})
	}
	sort.Slice(verbs, func(i, j int) bool {
		if verbs[i].count != verbs[j].count {
			return verbs[i].count > verbs[j].count
		}
		return verbs[i].verb < verbs[j].verb
	})
	for _, v := range verbs {
		fmt.Printf("  %-16s %d\n", v.verb, v.count)
	}
}

// renderBugReopenBlock prints the BUGS REOPENED section for the given counts.
func renderBugReopenBlock(bugTotal int, bugByDir map[string]int) {
	if bugTotal == 0 {
		return
	}
	fmt.Printf("\nBUGS REOPENED (last 7d): %d\n", bugTotal)
	type kv struct {
		dir   string
		count int
	}
	var dirs []kv
	for dir, c := range bugByDir {
		dirs = append(dirs, kv{dir, c})
	}
	sort.Slice(dirs, func(i, j int) bool {
		if dirs[i].count != dirs[j].count {
			return dirs[i].count > dirs[j].count
		}
		return dirs[i].dir < dirs[j].dir
	})
	for _, kv := range dirs {
		fmt.Printf("  %-20s %d\n", kv.dir, kv.count)
	}
}

// renderTracePercentilesBlock prints OP LATENCY when trace data exists.
func renderTracePercentilesBlock(ggDir string) {
	pcts, err := trace.ReadPercentiles(ggDir, 100)
	if err != nil || pcts.N == 0 {
		return
	}
	fmt.Printf("\nOP LATENCY (last %d spans — p50 %s  p95 %s  p99 %s)\n",
		pcts.N, trace.FmtMs(pcts.P50), trace.FmtMs(pcts.P95), trace.FmtMs(pcts.P99))
}
