package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/gurkangul/gg-cli/internal/config"
	"github.com/gurkangul/gg-cli/internal/store"
)

var statusRenderCmd = &cobra.Command{
	Use:   "render",
	Short: "Generate STATUS.md from gg brain state",
	Long: `Write STATUS.md to the project root, derived from live gg brain state.

  gg status render          # write STATUS.md
  gg status render --check  # exit non-zero if STATUS.md is stale (CI drift check)

The file begins with '<!-- GENERATED by gg status render. Do not edit. -->'
so any manual edit is visibly overwritten on the next run.`,
	RunE: runStatusRender,
}

var (
	statusRenderCheck bool
	statusRenderOut   string
)

func init() {
	statusRenderCmd.Flags().BoolVar(&statusRenderCheck, "check", false, "exit non-zero if STATUS.md differs from what render would produce (CI drift check)")
	statusRenderCmd.Flags().StringVar(&statusRenderOut, "output", "STATUS.md", "output file path (relative to project root)")
	statusCmd.AddCommand(statusRenderCmd)
}

func runStatusRender(cmd *cobra.Command, _ []string) error {
	d, err := loadDepsReadOnly(false)
	if err != nil {
		return err
	}
	defer d.Close()

	ctx, cancel := withTimeout(cmd.Context())
	defer cancel()

	// Gather data — each call is independent; partial failures degrade gracefully.
	tasks, _ := d.store.ListTasks(ctx, "")
	decisions, _ := d.store.ListDecisions(ctx, 10)
	rejections, _ := d.store.ListRejections(ctx, 5)
	messages, _ := d.store.GetInbox(ctx, "")

	cfg, cfgErr := config.Load()
	projectName := ""
	if cfgErr == nil {
		projectName = cfg.ProjectID[:8] // short UUID prefix
	}

	md := renderStatusMD(projectName, tasks, decisions, rejections, messages)

	// Resolve output path.
	outPath := statusRenderOut
	if !filepath.IsAbs(outPath) {
		ggDir, ggErr := config.GGDir()
		if ggErr != nil {
			return ggErr
		}
		outPath = filepath.Join(filepath.Dir(ggDir), outPath)
	}

	if statusRenderCheck {
		existing, readErr := os.ReadFile(outPath)
		if readErr != nil && !os.IsNotExist(readErr) {
			return fmt.Errorf("read %s: %w", outPath, readErr)
		}
		if string(existing) == md {
			fmt.Fprintf(cmd.ErrOrStderr(), "✓ STATUS.md is up to date\n")
			return nil
		}
		// Print a compact diff hint.
		fmt.Fprintf(cmd.ErrOrStderr(), "✗ STATUS.md is stale — run: gg status render\n")
		return fmt.Errorf("STATUS.md drift detected")
	}

	if writeErr := os.WriteFile(outPath, []byte(md), 0o644); writeErr != nil {
		return fmt.Errorf("write %s: %w", outPath, writeErr)
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "✓ STATUS.md written to %s\n", outPath)
	return nil
}

func renderStatusMD(projectID string, tasks []store.Task, decisions []store.Decision, rejections []store.Rejection, messages []store.Message) string {
	var b bytes.Buffer

	b.WriteString("<!-- GENERATED by gg status render. Do not edit. -->\n")
	fmt.Fprintf(&b, "<!-- Generated: %s -->\n\n", time.Now().UTC().Format(time.RFC3339))
	b.WriteString("# Project Status\n\n")

	// ── Active tasks ──────────────────────────────────────────────────────────
	b.WriteString("## Active Tasks\n\n")

	type pri struct{ name string; tasks []store.Task }
	byPriority := []pri{{"high", nil}, {"medium", nil}, {"low", nil}, {"", nil}}
	pMap := map[string]*[]store.Task{"high": &byPriority[0].tasks, "medium": &byPriority[1].tasks, "low": &byPriority[2].tasks}

	var blocked []store.Task
	for _, t := range tasks {
		switch t.Status {
		case "done":
			continue
		case "blocked":
			blocked = append(blocked, t)
		default:
			if list, ok := pMap[t.Priority]; ok {
				*list = append(*list, t)
			} else {
				byPriority[3].tasks = append(byPriority[3].tasks, t)
			}
		}
	}

	hasActive := false
	for _, p := range byPriority {
		if len(p.tasks) == 0 {
			continue
		}
		hasActive = true
		label := p.name
		if label == "" {
			label = "other"
		}
		fmt.Fprintf(&b, "### %s priority\n\n", strings.Title(label)) //nolint:staticcheck
		for _, t := range p.tasks {
			icon := "○"
			if t.Status == "in_progress" {
				icon = "→"
			}
			fmt.Fprintf(&b, "- %s **%s** %s\n", icon, t.ID, t.Title)
		}
		b.WriteString("\n")
	}
	if !hasActive {
		b.WriteString("_No active tasks._\n\n")
	}

	// ── Blocked tasks ─────────────────────────────────────────────────────────
	if len(blocked) > 0 {
		b.WriteString("## Blocked\n\n")
		for _, t := range blocked {
			fmt.Fprintf(&b, "- ⚠ **%s** %s", t.ID, t.Title)
			if t.BlockReason != "" {
				fmt.Fprintf(&b, " — %s", t.BlockReason)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// ── Recent decisions ──────────────────────────────────────────────────────
	if len(decisions) > 0 {
		b.WriteString("## Recent Decisions\n\n")
		for _, d := range decisions {
			text := d.Text
			if len(text) > 120 {
				text = text[:117] + "…"
			}
			fmt.Fprintf(&b, "- ✓ %s", text)
			if d.Reason != "" {
				reason := d.Reason
				if len(reason) > 80 {
					reason = reason[:77] + "…"
				}
				fmt.Fprintf(&b, " _(reason: %s)_", reason)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// ── Recent rejections ─────────────────────────────────────────────────────
	if len(rejections) > 0 {
		b.WriteString("## Recent Rejections\n\n")
		for _, r := range rejections {
			approach := r.Approach
			if len(approach) > 100 {
				approach = approach[:97] + "…"
			}
			fmt.Fprintf(&b, "- ✗ %s\n", approach)
		}
		b.WriteString("\n")
	}

	// ── Unread messages ───────────────────────────────────────────────────────
	if len(messages) > 0 {
		b.WriteString("## Unread Messages\n\n")
		for _, m := range messages {
			content := m.Content
			if len(content) > 100 {
				content = content[:97] + "…"
			}
			fmt.Fprintf(&b, "- [%s → %s] %s\n", m.FromRole, m.ToRole, content)
		}
		b.WriteString("\n")
	}

	if projectID != "" {
		fmt.Fprintf(&b, "---\n_Project: %s_\n", projectID)
	}

	return b.String()
}
