package parser

// Spike test: validates that ParseFile works end-to-end against a real
// .scip file produced by scip-go. The .scip file is expected at
// /tmp/gg-cli.scip (generated by: scip-go --output /tmp/gg-cli.scip).
//
// This test is skipped if the file does not exist (e.g. in CI without
// scip-go installed). The spike result is printed to verify document counts,
// symbol counts, and timing.

import (
	"context"
	"fmt"
	"os"
	"sync/atomic"
	"testing"
	"time"

	"github.com/gurkangul/gg-cli/internal/graph"
)

const spikeScipPath = "/tmp/gg-cli.scip"
const spikeLang = "go"

// spikeHandler counts events and records the first few symbols seen.
type spikeHandler struct {
	files   atomic.Int64
	symbols atomic.Int64
	refs    atomic.Int64
	samples []string // first few symbol names
}

func (h *spikeHandler) OnFile(_ context.Context, node *graph.Node) error {
	h.files.Add(1)
	return nil
}

func (h *spikeHandler) OnSymbol(_ context.Context, _ *graph.Node, symNode *graph.Node) error {
	n := h.symbols.Add(1)
	if n <= 5 {
		h.samples = append(h.samples, symNode.Properties["name"].(string))
	}
	return nil
}

func (h *spikeHandler) OnReference(_ context.Context, _ *graph.Node, sym string) error {
	h.refs.Add(1)
	return nil
}

// TestParseFile_Spike parses the real scip-go output and validates:
//  1. Non-zero file and symbol counts (parse is functional)
//  2. Wall time < 5 seconds for 10k-LOC class projects
//  3. ParseStreaming API works (github.com/scip-code/scip v0.7.0 confirmed)
func TestParseFile_Spike(t *testing.T) {
	if _, err := os.Stat(spikeScipPath); os.IsNotExist(err) {
		t.Skipf("spike scip file not found at %s — run: scip-go --output %s", spikeScipPath, spikeScipPath)
	}

	h := &spikeHandler{}
	ctx := context.Background()

	start := time.Now()
	if err := ParseFile(ctx, spikeScipPath, spikeLang, h); err != nil {
		t.Fatalf("ParseFile failed: %v", err)
	}
	elapsed := time.Since(start)

	files := h.files.Load()
	symbols := h.symbols.Load()
	refs := h.refs.Load()

	// Print spike results — visible with -v flag.
	fmt.Printf("\n=== SCIP Spike Results ===\n")
	fmt.Printf("  Indexer:  scip-go\n")
	fmt.Printf("  Input:    %s\n", spikeScipPath)
	fmt.Printf("  Files:    %d\n", files)
	fmt.Printf("  Symbols:  %d (definitions)\n", symbols)
	fmt.Printf("  Refs:     %d (references)\n", refs)
	fmt.Printf("  Parse:    %v\n", elapsed)
	if len(h.samples) > 0 {
		fmt.Printf("  Sample:   %v\n", h.samples)
	}
	fmt.Println()

	// Assertions
	if files == 0 {
		t.Error("parsed 0 files — SCIP output is empty or parse is broken")
	}
	if symbols == 0 {
		t.Error("parsed 0 symbols — definition extraction not working")
	}
	// Timing gate: <5s for a project of this size.
	// The target is <5s for 10k LOC; this project is ~2k LOC so should be much faster.
	if elapsed > 5*time.Second {
		t.Errorf("parse took %v, target is <5s for 10k LOC — check streaming implementation", elapsed)
	}
}
